name: 'Publish modules'

on:
  workflow_call:
    inputs:
      target-module:
        required: true
        type: string
      target-ref:
        required: true
        type: string

jobs:
  publish:
    name: Publish artifacts with Gradle
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.target-ref }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Verify source integrity
        run: |
          ./gradlew ${{ inputs.target-module }}:clean ${{ inputs.target-module }}:build -x check

      - name: Publish artifacts
        run: |
          ./gradlew ${{ inputs.target-module }}:jreleaserConfig \
          ${{ inputs.target-module }}:publish \
          ${{ inputs.target-module }}:jreleaserDeploy
        env:
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
          JRELEASER_NEXUS2_USERNAME: ${{ secrets.JRELEASER_CENTRAL_USERNAME }}
          JRELEASER_NEXUS2_PASSWORD: ${{ secrets.JRELEASER_CENTRAL_PASSWORD }}
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.JRELEASER_CENTRAL_USERNAME }}
          JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.JRELEASER_CENTRAL_PASSWORD }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
